require_relative 'employee.rb'
require_relative 'owner.rb'
require_relative 'commission_sales_person.rb'
require_relative 'quota_sales_person.rb'
require_relative 'sales_person.rb'
require_relative 'sale.rb'
require_relative 'company.rb'
require 'csv'
require 'pry'

